apiVersion: v1
kind: Secret
metadata:
  name: configclient
  namespace: robinfo
  labels:
    pepr.dev/keycloak: createclient
data:
  id: ZGV2XzAwZWI4OTA0LTViODgtNGM2OC1hZDY3LWNlYzBkMmUwN2FhNl9yb2JpbmZv
  name: cm9iaW5mbw==
  domain: YmlnYmFuZy5kZXY=
  realm: YmFieS15b2Rh